"""
logger.py — Paper Trading Logger Module (SQLite)

Stores every signal-to-exit lifecycle for XAUUSD/EURUSD Liquidity Sweep V2.
Written BEFORE sending the order (entry_planned / stop / target known),
then UPDATED after the order fills and exits.

Schema columns (all nullable except event_id):

  event_id               TEXT PRIMARY KEY   — UUID v4, generated by log_signal()
  asset                  TEXT               — e.g. "XAUUSD" or "EURUSD"
  signal_time            TEXT (ISO-8601)    — when the signal engine fired
  confirmation_time      TEXT (ISO-8601)    — when the signal was confirmed
  features_json          TEXT               — JSON blob of signal features
  rule_score             REAL               — rule-based entry score
  model_probability      REAL               — model probability (0–1)
  entry_planned          REAL               — planned entry price
  stop_planned           REAL               — planned stop-loss price
  target_planned         REAL               — planned take-profit price
  order_sent_time        TEXT (ISO-8601)    — when the order was dispatched
  entry_actual           REAL               — actual fill price
  slippage_actual        REAL               — slippage = entry_actual - entry_planned (signed)
  exit_time              TEXT (ISO-8601)    — when the trade exited
  exit_price             REAL               — actual exit price
  exit_reason            TEXT               — e.g. "take_profit", "stop_loss", "manual_close"
  mfe_r                  REAL               — maximum favourable excursion in R multiples
  mae_r                  REAL               — maximum adverse excursion in R multiples
  net_result_r           REAL               — net result in R multiples
  automation_level       INTEGER            — 0=manual, 1=semi-auto, 2=full-auto
  kill_switch_status_at_signal  INTEGER     — 0=off, 1=on (blocking)

Dependencies: Python 3.10+ standard library only (sqlite3, uuid, datetime).
"""

import sqlite3
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

# ---------------------------------------------------------------------------
# Default database path (sibling to this file)
# ---------------------------------------------------------------------------
DEFAULT_DB_PATH = Path(__file__).resolve().parent / "paper_trading.db"


def _iso_now() -> str:
    """Return current UTC timestamp as ISO-8601 string."""
    return datetime.now(timezone.utc).isoformat()


# ---------------------------------------------------------------------------
# Schema DDL
# ---------------------------------------------------------------------------

_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS signals (
    event_id                TEXT PRIMARY KEY,
    asset                   TEXT,
    signal_time             TEXT,
    confirmation_time       TEXT,
    features_json           TEXT,
    rule_score              REAL,
    model_probability       REAL,
    entry_planned           REAL,
    stop_planned            REAL,
    target_planned          REAL,
    order_sent_time         TEXT,
    entry_actual            REAL,
    slippage_actual         REAL,
    exit_time               TEXT,
    exit_price              REAL,
    exit_reason             TEXT,
    mfe_r                   REAL,
    mae_r                   REAL,
    net_result_r            REAL,
    automation_level        INTEGER,
    kill_switch_status_at_signal INTEGER
);
"""


# ---------------------------------------------------------------------------
# Connection management
# ---------------------------------------------------------------------------

def _get_connection(db_path: Optional[str] = None) -> sqlite3.Connection:
    """Return a sqlite3 connection to *db_path* (or DEFAULT_DB_PATH).

    Sets ``row_factory`` to ``sqlite3.Row`` so that cursor fetch methods
    return dictionary-like rows (usable via ``dict(row)``).
    """
    path = db_path if db_path is not None else str(DEFAULT_DB_PATH)
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL;")       # safe concurrent reads
    conn.execute("PRAGMA foreign_keys=ON;")
    return conn


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def init_db(db_path: Optional[str] = None) -> str:
    """Create the SQLite database and ``signals`` table if they do not exist.

    Args:
        db_path: Full path to the ``.db`` file.  Defaults to
                 ``paper_trading.db`` in the same directory as this module.

    Returns:
        The absolute path of the database file.
    """
    path = Path(db_path) if db_path else DEFAULT_DB_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    conn = _get_connection(str(path))
    conn.executescript(_SCHEMA_SQL)
    conn.commit()
    conn.close()
    return str(path.resolve())


def log_signal(
    asset: str,
    signal_time: str,
    confirmation_time: str,
    features_json: str,
    rule_score: float,
    model_probability: float,
    entry_planned: float,
    stop_planned: float,
    target_planned: float,
    order_sent_time: str,
    automation_level: int,
    kill_switch_status_at_signal: int,
    *,
    event_id: Optional[str] = None,
    db_path: Optional[str] = None,
) -> dict[str, Any]:
    """Insert a new signal record and return it as a dictionary.

    Call this **BEFORE** sending the order to the execution layer so that
    the planned entry / stop / target are persisted before any fill data
    arrives.

    Args:
        asset: Instrument name, e.g. ``"XAUUSD"`` or ``"EURUSD"``.
        signal_time: ISO-8601 timestamp when the signal engine fired.
        confirmation_time: ISO-8601 timestamp when the signal was confirmed.
        features_json: Arbitrary JSON blob of signal features.
        rule_score: Scalar score from the rule-based component.
        model_probability: Model probability in [0, 1].
        entry_planned: Planned entry price.
        stop_planned: Planned stop-loss price.
        target_planned: Planned take-profit price.
        order_sent_time: ISO-8601 timestamp when the order was dispatched.
        automation_level: 0=manual, 1=semi-auto, 2=full-auto.
        kill_switch_status_at_signal: 0=off, 1=on.
        event_id: Optional caller-supplied UUID; a new UUID v4 is generated
                  if omitted.
        db_path: Override the database path.

    Returns:
        A dictionary representation of the inserted row.
    """
    eid = event_id if event_id is not None else str(uuid.uuid4())
    conn = _get_connection(db_path)
    try:
        conn.execute(
            """
            INSERT INTO signals (
                event_id, asset, signal_time, confirmation_time,
                features_json, rule_score, model_probability,
                entry_planned, stop_planned, target_planned,
                order_sent_time, automation_level,
                kill_switch_status_at_signal
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                eid,
                asset,
                signal_time,
                confirmation_time,
                features_json,
                rule_score,
                model_probability,
                entry_planned,
                stop_planned,
                target_planned,
                order_sent_time,
                automation_level,
                kill_switch_status_at_signal,
            ),
        )
        conn.commit()
        return _row_to_dict(
            conn.execute(
                "SELECT * FROM signals WHERE event_id = ?", (eid,)
            ).fetchone()
        )
    finally:
        conn.close()


def update_order_result(
    event_id: str,
    entry_actual: float,
    slippage_actual: float,
    exit_time: str,
    exit_price: float,
    exit_reason: str,
    mfe_r: float,
    mae_r: float,
    net_result_r: float,
    *,
    db_path: Optional[str] = None,
) -> Optional[dict[str, Any]]:
    """Update a previously logged signal with actual fill and exit data.

    Call this **AFTER** the trade closes to fill in the execution outcome.

    Args:
        event_id: The UUID of the signal to update.
        entry_actual: Actual fill price.
        slippage_actual: Signed difference (entry_actual - entry_planned).
        exit_time: ISO-8601 timestamp of exit.
        exit_price: Price at exit.
        exit_reason: Categorical reason.
        mfe_r: Maximum favourable excursion in R multiples.
        mae_r: Maximum adverse excursion in R multiples.
        net_result_r: Net result in R multiples.
        db_path: Override the database path.

    Returns:
        The updated row as a dictionary, or ``None`` if *event_id* is not
        found.
    """
    conn = _get_connection(db_path)
    try:
        cursor = conn.execute(
            """
            UPDATE signals
            SET entry_actual      = ?,
                slippage_actual   = ?,
                exit_time         = ?,
                exit_price        = ?,
                exit_reason       = ?,
                mfe_r             = ?,
                mae_r             = ?,
                net_result_r      = ?
            WHERE event_id = ?
            """,
            (
                entry_actual,
                slippage_actual,
                exit_time,
                exit_price,
                exit_reason,
                mfe_r,
                mae_r,
                net_result_r,
                event_id,
            ),
        )
        conn.commit()
        if cursor.rowcount == 0:
            return None
        return _row_to_dict(
            conn.execute(
                "SELECT * FROM signals WHERE event_id = ?", (event_id,)
            ).fetchone()
        )
    finally:
        conn.close()


def get_recent_trades(
    asset: str,
    n: int = 20,
    *,
    db_path: Optional[str] = None,
) -> list[dict[str, Any]]:
    """Return the *n* most recent trades for a given asset.

    Only rows that have an ``exit_time`` (i.e. completed trades) are
    returned, ordered by ``order_sent_time DESC``.

    Args:
        asset: Instrument name (e.g. ``"XAUUSD"``).
        n: Maximum number of rows (default 20).
        db_path: Override the database path.

    Returns:
        A list of row dictionaries (most recent first).
    """
    conn = _get_connection(db_path)
    try:
        rows = conn.execute(
            """
            SELECT * FROM signals
            WHERE asset = ? AND exit_time IS NOT NULL
            ORDER BY order_sent_time DESC
            LIMIT ?
            """,
            (asset, n),
        ).fetchall()
        return [_row_to_dict(r) for r in rows]
    finally:
        conn.close()


def get_all_trades(
    *,
    db_path: Optional[str] = None,
) -> list[dict[str, Any]]:
    """Return every signal row in the database.

    Rows are ordered by ``order_sent_time DESC`` so the most recent
    appears first.

    Args:
        db_path: Override the database path.

    Returns:
        A list of all row dictionaries.
    """
    conn = _get_connection(db_path)
    try:
        rows = conn.execute(
            "SELECT * FROM signals ORDER BY order_sent_time DESC"
        ).fetchall()
        return [_row_to_dict(r) for r in rows]
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _row_to_dict(row: sqlite3.Row) -> dict[str, Any]:
    """Convert a ``sqlite3.Row`` to a plain ``dict``.

    If *row* is ``None``, returns an empty dict (should not happen with
    valid queries, but guards against callers that check truthiness).
    """
    if row is None:
        return {}
    return dict(row)